"""
config.py
---------
One place for every path, label, and setting the pipeline uses.
Change things here instead of hunting through 3 different scripts.
"""

import os

# ── Paths ──────────────────────────────────────────────────────────
# Everything is relative to this file, so the project runs the same
# no matter which machine (laptop / college PC) you clone it onto.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_DIR = os.path.join(DATA_DIR, "raw")
PROCESSED_DIR = os.path.join(DATA_DIR, "processed")
MODEL_DIR = os.path.join(BASE_DIR, "models", "best_model")
RESULTS_DIR = os.path.join(BASE_DIR, "results")

for d in [RAW_DIR, PROCESSED_DIR, os.path.dirname(MODEL_DIR), RESULTS_DIR]:
    os.makedirs(d, exist_ok=True)

# ── Labels ─────────────────────────────────────────────────────────
LABEL2ID = {"negative": 0, "neutral": 1, "positive": 2}
ID2LABEL = {v: k for k, v in LABEL2ID.items()}
NUM_LABELS = 3

# ── Raw dataset files ────────────────────────────────────────────────
# Just drop these files into data/raw/ with these exact names.
# See README.md for the download link for each one.
RAW_FILES = {
    "sentiment140": "sentiment140.csv",
    "social_media_sentiments": "social_media_sentiments.csv",
    "hf_sentiment": "hf_sentiment_analysis.csv",
    # no file needed for "synthetic" - it's generated in code
    # "viral_content" was intentionally dropped - see README
    # ("Image engagement scoring" section) for why.
}

# ── Structured dataset schema ────────────────────────────────────────
# Every row that leaves 01_data_preprocessing.py has exactly these
# columns, so we always know where a row came from and how its label
# was produced (instead of an anonymous text,label table).
SCHEMA_COLUMNS = [
    "text",            # cleaned text
    "label",           # negative / neutral / positive
    "label_id",        # 0 / 1 / 2
    "source",          # which dataset the row came from (key of SOURCE_INFO)
    "label_method",    # how the label was produced (see SOURCE_INFO)
    "is_synthetic",    # True if the TEXT itself was generated by us
    "original_label",  # the label exactly as it appeared in the source
]

# Provenance of each source. `label_method` values:
#   provided_3class - dataset ships its own negative/neutral/positive labels
#   emotion_mapped  - fine-grained emotion label mapped by us onto 3 classes
#   emoticon        - distant supervision: label derived automatically from
#                     emoticons in the tweet (Sentiment140), NOT human-annotated
#   template        - text AND label generated by our own templates
SOURCE_INFO = {
    "sentiment140":            {"label_method": "emoticon",        "is_synthetic": False},
    "social_media_sentiments": {"label_method": "emotion_mapped",  "is_synthetic": False},
    "hf_sentiment":            {"label_method": "provided_3class", "is_synthetic": False},
    "synthetic_marketing":     {"label_method": "template",        "is_synthetic": True},
    "factual_neutral":         {"label_method": "template",        "is_synthetic": True},
}

# Validation + test rows are drawn ONLY from these sources, so reported
# accuracy reflects real text rather than our own templates (which would
# inflate it). Synthetic rows are used for training only.
EVAL_SOURCES = [k for k, v in SOURCE_INFO.items() if not v["is_synthetic"]]
EVAL_FRACTION = 0.2  # share of the final dataset held out for val+test (split 50/50)

# How many rows to keep PER CLASS after combining everything.
# Keeps training time reasonable on a laptop CPU. Raise this when
# running on a college GPU machine.
ROWS_PER_CLASS = int(os.environ.get("SENTIMENT_ROWS_PER_CLASS", 8000))

# ── Model ──────────────────────────────────────────────────────────
# distilbert is ~40% faster than BERT/RoBERTa and fine on a laptop CPU.
# Swap to "cardiffnlp/twitter-roberta-base-sentiment-latest" when you
# have GPU access (college lab) for a real accuracy boost.
MODEL_NAME = os.environ.get("SENTIMENT_MODEL_NAME", "distilbert-base-uncased")

MAX_LENGTH = 128
SEED = 42

# ── Instagram authenticity audit (08_instagram_audit.py) ─────────────
INSTAGRAM_AUDIT = {
    "raw_file": os.environ.get("INSTAGRAM_RAW_FILE", "instagram_influencer.csv"),  # in data/raw/
    "out_dir": os.path.join(RESULTS_DIR, "instagram_audit"),
    "min_rows": 30,
    # candidate column names (lower-case, spaces/hyphens -> underscore)
    "columns": {
        "likes": ["likes", "like_count", "likes_count", "n_likes", "num_likes", "number_of_likes"],
        "comments": ["comments", "comment_count", "comments_count", "n_comments", "num_comments", "number_of_comments"],
        "followers": ["followers", "follower_count", "followers_count", "n_followers", "num_followers", "number_of_followers"],
        "timestamp": ["timestamp", "date", "datetime", "created_at", "posted_at", "taken_at", "post_date", "time", "upload_date"],
        "caption": ["caption", "text", "description", "post_text", "post_caption"],
        "image": ["image", "image_path", "image_file", "image_url", "img", "img_path", "filename", "file_name", "media_url", "display_url"],
        "group": ["username", "user", "account", "owner", "influencer", "handle", "profile", "category", "niche"],
    },
    "thresholds": {
        "uniform_band": (0.95, 1.05), "uniform_band_warn": (0.85, 1.15), "min_skew": 1.0,
        "benford_p_fail": 0.01, "benford_p_warn": 0.05,
        "benford_mad_fail": 0.015, "benford_mad_warn": 0.012, "benford_min_span": 2.0,
        "corr_pass": 0.3, "corr_warn": 0.1,
        "ratio_over1_warn": 0.05, "ratio_over1_fail": 0.25,
        "eng_over1_warn": 0.05, "eng_over1_fail": 0.20,
        "likes_gt_f_warn": 0.05, "likes_gt_f_fail": 0.25,
        "future_fail": 0.01,
        "dup_caption_warn": 0.10, "dup_caption_fail": 0.50,
        "dup_image_warn": 0.01, "dup_image_fail": 0.10,
        "group_spread_fail": 1.3, "group_eta_warn": 0.05,
    },
}

# ── Website SEO/GEO analysis (09_website_analysis.py) ─────────────────
WEBSITE_ANALYSIS = {
    "timeout": 12,                 # seconds per HTTP request
    "user_agent": ("SentimentStudio-SEO-GEO-Audit/1.0 "
                   "(+https://github.com/kashvi1504/AI-Driven-Multimodal-Marketing-Assistant)"),
    "max_link_checks": 20,         # links sampled for the broken-link check
    "max_bytes": 5_000_000,        # refuse pages larger than this
    # Optional: Google PageSpeed Insights works without a key but is rate-limited.
    # Get a free key at https://developers.google.com/speed/docs/insights/v5/get-started
    "pagespeed_api_key": os.environ.get("PAGESPEED_API_KEY", ""),
    "pagespeed_strategy": os.environ.get("PAGESPEED_STRATEGY", "mobile"),  # or "desktop"
    "pagespeed_timeout": 90,
    "ai_crawlers": ["GPTBot", "ClaudeBot", "PerplexityBot", "Google-Extended"],
}
